FROM electronuserland/electron-builder:wine

RUN \
  apt-get update && \
  apt-get install --no-install-recommends -y \
    \
    less \
    file \
    \
  && \
  apt-get remove software-properties-common -y && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# RUN \
  # npm i -g \
  #   eslint \
  #   uglify-js && \
RUN \
  node --version && \
  npm --version && \
  yarn --version

WORKDIR /work
