FROM electronuserland/builder:wine

RUN \
  apt-get update && \
  apt-get install --no-install-recommends -y \
    \
    less \
    file \
    ruby-dev \
    \
  && \
  gem install dpl && \
  apt-get purge -y \
    ruby-dev \
    \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# RUN \
  # npm i -g \
  #   eslint \
  #   uglify-js && \
RUN \
  node --version && \
  npm --version && \
  yarn --version
